### ISSUE TITLE
[BUG] [Critical] Cannot build with UE 4.26.1

### ISSUE THREAD

**Issue by Saibamen** [OpenTournament/OpenTournament#221]
**Bug Description**

Tested on bb05bfd and df8e4d4

Error while rebuilding solution:

```
Error	LNK2019	unresolved external symbol "__declspec(dllimport) void __cdecl UE4PushModelPrivate::MarkPropertyDirty(int,int)" (__imp_?MarkPropertyDirty@UE4PushModelPrivate@@YAXHH@Z) referenced in function "public: virtual void __cdecl AUR_PlayerState::AddDeath(class AController *)" (?AddDeath@AUR_PlayerState@@UEAAXPEAVAController@@@Z)	OpenTournament	D:\Unreal Engine Projects\OpenTournament\Intermediate\ProjectFiles\Module.OpenTournament.cpp.obj	1
```

And also 2 warnings:

```
Source/OpenTournament/UR_AbilitySystemComponent.cpp(40): warning C4996: 'UAbilitySystemComponent::OwnerActor': This will be made private in future engine versions. Use SetOwnerActor or GetOwnerActor instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
```

```
Source/OpenTournament/UR_Character.cpp(426): warning C4996: 'TBaseDelegate': TBaseDelegate<ReturnType, ArgTypes...> is deprecated - use TDelegate<ReturnType(ArgTypes...)> instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
```

Visual Studio 16.8.6

**To Reproduce**
1. Have latest Unreal Engine
2. Create Visual Studio solution files
3. Open VS, right click on solution name in Solution Explorer and click Rebuild Solution

**Expected Behavior**
Solution can be rebuild without warnings and errors

**Additional Information:**
 - Build Type: Development
 - Version Information (Build Number, GitHub revision): bb05bfd
 - OS [e.g. Windows, Mac, Linux]: Windows
 - Hardware [if applicable]: -

**Comment by wail** [comment]
Project is currently targeting UE4.25, are you unable to build using that engine version?

**Comment by Saibamen** [comment]
Don't know. I already uninstalled old UE version

**Comment by ChatouilleGG** [comment]
Upgraded unstable to 4.27
